http_server:
  address: "localhost"
  port: "80"

database:
  driver: "mysql"
  address: ""
  user: "root"
  name: "smart-toy-db"
  password: "password"
  ssl_mode: "enbled"

redis:
  address: "localhost:6379"
  password: ""
  database: 0

jwt:
  access_life: 1
  refresh_life: 1
  jwt_secret_key: "no-secret"

upload_dir: "/path/to/upload/dir"

smart_toy:
  max_count: 100